# Generated by Django 2.0.4 on 2018-04-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spacyal', '0005_auto_20180410_1508'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('hash', 'suggestion', 'project')},
        ),
    ]
