# Generated by Django 2.0.8 on 2018-08-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spacyal', '0007_auto_20180802_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_f1', models.FloatField(blank=True, null=True)),
                ('eval_precission', models.FloatField(blank=True, null=True)),
                ('eval_recall', models.FloatField(blank=True, null=True)),
                ('model_path', models.CharField(max_length=255)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('cases_evaluation', models.ManyToManyField(blank=True, null=True, related_name='cases_evaluation', to='spacyal.case')),
                ('cases_training', models.ManyToManyField(related_name='cases_training', to='spacyal.case')),
            ],
        ),
        migrations.AddField(
            model_name='al_project',
            name='evaluation_share',
            field=models.FloatField(blank=True, help_text='specify a share of decided cases to use for evaluation', null=True, verbose_name='share of evaluation cases'),
        ),
        migrations.AddField(
            model_name='project_history',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spacyal.al_project'),
        ),
    ]
