# Generated by Django 2.0.8 on 2018-08-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacyal', '0008_auto_20180809_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_history',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
